install.packages('usethis')
usethis::use_git()
#Hola mundo
gitcreds::gitcreds_set()
usethis::use_github()
gitcreds::gitcreds_set()
usethis::use_github()
usethis::use_github(private = FALSE)
###CARPETAS
dir.create("data/raw", recursive = TRUE)
dir.create("data/processed", recursive = TRUE)
dir.create("data/sources", recursive = TRUE)
dir.create("outputs/figures", recursive = TRUE)
dir.create("outputs/tables", recursive = TRUE)
dir.create("outputs/chart_catalog", recursive = TRUE)
dir.create("scripts/data-cleaning", recursive = TRUE)
dir.create("scripts/plots", recursive = TRUE)
dir.create("scripts/templates", recursive = TRUE)
dir.create("data/raw/enemdu/evolucion", recursive = TRUE)